# Generated by Django 5.2.2 on 2025-08-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت واحد (در زمان ثبت)'),
            preserve_default=False,
        ),
    ]
